"""initial tables with auth and platform

Revision ID: c8a59b8ff950
Revises: 
Create Date: 2026-02-16 10:15:24.827734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c8a59b8ff950'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('igdb_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cover_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_cache_igdb_id'), 'games_cache', ['igdb_id'], unique=True)
    op.create_index(op.f('ix_games_cache_name'), 'games_cache', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('user_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('igdb_id', sa.Integer(), nullable=False),
    sa.Column('platform_igdb_id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games_cache.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'igdb_id', 'platform_igdb_id', name='uq_user_game_platform')
    )
    op.create_index(op.f('ix_user_games_game_id'), 'user_games', ['game_id'], unique=False)
    op.create_index(op.f('ix_user_games_igdb_id'), 'user_games', ['igdb_id'], unique=False)
    op.create_index(op.f('ix_user_games_user_id'), 'user_games', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_games_user_id'), table_name='user_games')
    op.drop_index(op.f('ix_user_games_igdb_id'), table_name='user_games')
    op.drop_index(op.f('ix_user_games_game_id'), table_name='user_games')
    op.drop_table('user_games')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_games_cache_name'), table_name='games_cache')
    op.drop_index(op.f('ix_games_cache_igdb_id'), table_name='games_cache')
    op.drop_table('games_cache')
    # ### end Alembic commands ###
